trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
    displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@16.x
    npm install
    ng build --prod
  displayName: 'Install and Build Angular'
