variables:
  SSH_SERVICE_CONNECTION_USERNAME: 'tomcat'
  SSH_SERVICE_CONNECTION_SERVER: '103.240.89.139'
  SSH_SERVICE_CONNECTION_PORT: '9007'
  SSH_SERVICE_CONNECTION_PATH: '/opt/emanager-uat/tomcat9/anplapps/ROOT/eMSAAS-az'


trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@16.x
    npm install
    ng build 
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build artifacts'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/angular-app.zip'
    replaceExistingArchive: true
  displayName: 'Archive build artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'


- script: |
    scp -r -P $(SSH_SERVICE_CONNECTION_PORT) ./angular-app.zip $(SSH_SERVICE_CONNECTION_USERNAME)@$(SSH_SERVICE_CONNECTION_SERVER):$(SSH_SERVICE_CONNECTION_PATH)
    ssh -p $(SSH_SERVICE_CONNECTION_PORT) $(SSH_SERVICE_CONNECTION_USERNAME)@$(SSH_SERVICE_CONNECTION_SERVER) "cd $(SSH_SERVICE_CONNECTION_PATH) && unzip -o angular-app.zip && rm angular-app.zip"
  displayName: 'Deploy to Linux Server'
